### ISSUE TITLE
好像不行了？

### ISSUE THREAD

**Issue by wby238** [bubao/GetZhiHuZhuanLan#2]
npm install之后出现下面的log：
```log
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file G:\git\GetZhiHuZhuanLan\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'l' at 16:6
npm ERR!     "lodash": "^4.17.4",
npm ERR!      ^
npm ERR! File: G:\git\GetZhiHuZhuanLan\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     G:\git\GetZhiHuZhuanLan\npm-debug.log
```
还有输出的文件：
```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Finishing
10 silly install printInstalled
11 verbose stack Error: Failed to parse json
11 verbose stack Unexpected token 'l' at 16:6
11 verbose stack     "lodash": "^4.17.4",
11 verbose stack      ^
11 verbose stack     at parseError (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
11 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
11 verbose stack     at tryToString (fs.js:456:3)
11 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
12 verbose cwd G:\git\GetZhiHuZhuanLan
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
15 error node v6.11.1
16 error npm  v3.10.10
17 error file G:\git\GetZhiHuZhuanLan\package.json
18 error code EJSONPARSE
19 error Failed to parse json
19 error Unexpected token 'l' at 16:6
19 error     "lodash": "^4.17.4",
19 error      ^
20 error File: G:\git\GetZhiHuZhuanLan\package.json
21 error Failed to parse package.json data.
21 error package.json must be actual JSON, not just JavaScript.
21 error
21 error This is not a bug in npm.
21 error Tell the package author to fix their package.json file. JSON.parse
22 verbose exit [ 1, true ]

```

**Comment by bubao** [comment]
解决了，主要是我把package.json格式写错了，一直没注意。
现在这个项目迁移到[nodc](https://github.com/bubao/nodc)，不过win上还未测试过。

## 解决方法

### 方法一
直接用下面的方法同步我的仓库，再安装依赖
```
git clone https://github.com/bubao/GetZhiHuZhuanLan.git

npm i
```

### 方法二：
直接复制下面的配置覆盖原来的`package.json`,再`npm i`安装依赖。

```
{
  "name": "ZhihuZhuanlan",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node src/index.js && node src/MD.js"
  },
  "author": "bubao",
  "license": "ISC",
  "dependencies": {
    "cheerio": "^0.22.0",
    "h2m": "^0.5.2",
    "lodash": "^4.17.4",
    "request": "^2.81.0"
  }
}
```

**Comment by wby238** [comment]
能用了，thx
